name: Release

on:
  push:
    tags:
      - "*" # 任何 tag 推送时触发

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package NetOptimize.zip
        shell: bash
        run: |
          zip -r NetOptimize.zip boot-completed.sh module.prop

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: NetOptimize.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
